demo:
  rocketmq:
    enabled: true

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:192.168.207.128:9876}
  producer:
    group: ${ROCKETMQ_PRODUCER_GROUP:course-demo-producer-group}
    send-message-timeout: 3000

